### ISSUE TITLE
"Error"  Message stated on bottom right of the FBW Installer

### ISSUE THREAD

**Issue by Terrisc61077** [flybywiresim/installer#421] opened 2023-01-20 02:59 UTC
### Aircraft Version

Development

### Build info

```json
0
```

### Describe the bug

wont allow aircraft to load in the sim

### Expected behavior

Load

### Steps to reproduce

Opemed the instatller

**Comment by Benjozork** [comment] 2023-01-20 03:20
I transferred this to the right repository.

Can you provide the following:

1. Screenshot of the **Settings (bottom right, wheel icon) > About** page of the installer
2. Logs obtained using the following method (in the same installer session as facing the issue):
3. 
![image](https://user-images.githubusercontent.com/4503241/213610756-4ac7519d-e0c6-478e-a6ba-f8d4a4efcf23.png)

**Comment by Terrisc61077** [comment] 2023-01-20 03:26
![Error status](https://user-images.githubusercontent.com/57339951/213611001-e7cd7546-869e-4fc4-8df6-71bacb97193a.jpg)

**Comment by RoyalxFalcon** [comment] 2023-01-26 09:45
Same issue with me

![Untitled](https://user-images.githubusercontent.com/123629873/214804920-7c100aa6-f145-4065-a881-a5f4c590d18e.jpg)
[-1674725936427.log](https://github.com/flybywiresim/installer/files/10508025/-1674725936427.log)

**Comment by FoxtrotSierra6829** [comment] 2023-01-28 22:13
> I transferred this to the right repository.
> 
> Can you provide the following:
> 
>     1. Screenshot of the **Settings (bottom right, wheel icon) > About** page of the installer
> 
>     2. Logs obtained using the following method (in the same installer session as facing the issue):
> 
> 
> ![image](https://user-images.githubusercontent.com/4503241/213610756-4ac7519d-e0c6-478e-a6ba-f8d4a4efcf23.png)

please read the above

**Comment by RoyalxFalcon** [comment] 2023-01-29 09:01
________________________________

**Comment by FoxtrotSierra6829** [comment] 2024-04-01 10:19
Closing as stale. If the issue is still persisting, please reopen the issue

**Closed by FoxtrotSierra6829** 2024-04-01 10:19 UTC
Labels: Bug
