### ISSUE TITLE
Autostart

### ISSUE THREAD

**Issue by Hypeism** [flybywiresim/installer#317] opened 2021-11-09 21:52 UTC
### Installer Version

1.2.0

### Description

Add an option to enable/disable automatic launch of the installer on PC startup

### Discord Username (optional)

◯[Z+85-∫₀⁹⁰secxsin²xdx/(1+secx)]

**Comment by FoxtrotSierra6829** [comment] 2021-11-18 08:46
Partially duplicate of #105 , thus modifying this issue to only cover autostart

**Comment by ErickSharp** [comment] 2021-12-24 04:42
This feature is coming in version 3 of the installer! 😊

**Comment by aighes** [comment] 2022-03-22 04:22
Maybe it's a better idea to have a command-line switch. Like if you run FlyByWire Installer.exe --update_a32nx it won't start the gui of the installer but just show a progress bar and updates the A32nx based on the settings done before in the installer.

**Comment by ErickSharp** [comment] 2022-03-22 06:19
> Maybe it's a better idea to have a command-line switch. Like if you run FlyByWire Installer.exe --update_a32nx it won't start the gui of the installer but just show a progress bar and updates the A32nx based on the settings done before in the installer.

I don't think that's necessarily something we are currently interested in doing. The whole point of our installer is to be a friendly GUI to make it easier for non-technical users to install their aircraft.

**Closed** 2022-04-12 19:29 UTC
Labels: Request
