### ISSUE TITLE
Installer does not perform an update,

### ISSUE THREAD

**Issue by CaptainUwe27** [flybywiresim/installer#193] opened 2021-03-26 07:47 UTC
**Mod Version**

**Describe the bug**

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by FoxtrotSierra6829** [comment] 2021-03-26 14:36
Possible duplicate of #179

**Comment by nistei** [comment] 2021-03-26 15:14
@CaptainUwe27 @Kamegohan can you test the method described in: https://github.com/flybywiresim/installer/issues/179#issuecomment-807380531

We are going to release a new version very soon.

**Comment by Kamegohan** [comment] 2021-03-26 15:29
@nistei 
although everything's works well again, I will try to follow up your recommended commit. Will answer in the #179 thread

**Comment by Kamegohan** [comment] 2021-03-26 15:58
Additional information here: initial problem was that the installer (V1.05) itself did not update although the "downloading update" bar appeared on the title-bar of the installer. Re-starting did not change anything. So I downloaded V1.1 from the website and installed it without deinstalling old version. From this moment everything worked smooth and fine again

**Comment by CaptainUwe27** [comment] 2021-03-26 16:56
Hi Kevin, 

thanks fort he answer.

 

Your Name sounds german. When it is right, we can write in german, i´m a German man too.

 

If not, not matter, we write in English.

I have already uninstalled the installer several times and reinstalled the installer from the homepage.

I have also downloaded the developer version individually from the homepage. This works and is also installed correctly in the community folder. 

If I then click on the installer again, then I am offered the full version as a download. I click on it, the download takes place and at the very end then appears, Oops, something went wrong.

Until the update to 1.11 everything went smoothly for me. 

 

Regards, Uwe (CaptainUwe27)

 

 

Von: Kevin Diehl ***@***.***> 
Gesendet: Freitag, 26. März 2021 16:30
An: flybywiresim/installer ***@***.***>
Cc: CaptainUwe27 ***@***.***>; Mention ***@***.***>
Betreff: Re: [flybywiresim/installer] Installer does not perform an update, (#193)

 

@nistei <https://github.com/nistei> 
although everything's works well again, I will try to follow up your recommended commit. Will answer in the #179 <https://github.com/flybywiresim/installer/issues/179>  thread

**Comment by Kamegohan** [comment] 2021-03-26 17:47
Hi Uwe,

you are right, I am from Germany. Due to the international community I will answer in English and German (way more below).

Have you tried to install the official installer only or did you used the provided installer from [(https://github.com/flybywiresim/installer/issues/179#issuecomment-807380531)] ?
There seem to be some problems with the "old" (official) installer.

Please install the Version 1.1.3-rc1 and try again to download the plane.
Maybe you will have to edit the path to your community folder in the settings.

If this will not work maybe you have an Discord Username for us, so we won't abuse Github as a forum? Or maybe you can contact me directly here (I am new to Github and don't know how to send private messages).

German:
Bitte versuche aus dem oben genannten Link mal die Vorabversion des neuen Installers zu installieren. Das ist eine noch nicht veröffentlichte Version, bei der die Probleme aus dem offiziellen Installer gelöst wurden. Die Version ist Version 1.1.3-rc1. Du brauchst den alten Installer nicht deinstallieren. Einfach den neuen "drüberbügeln" und testen. Eventuell musst du noch den Pfad zum Community Ordner richtig abändern.

Falls das nicht klappt, sollten wir schauen, dass wir Github nicht als Forum missbrauchen und uns für alles Weitere im Discord austauschen. Oder du kontaktierst mich hier über eine Privatnachricht (falls es das gibt. Bin selbst noch neu hier und habe eine solche Funktion noch nicht gefunden.)

Best regards / Grüße
Kevin

**Comment by CaptainUwe27** [comment] 2021-03-26 18:34
Hallo (Hi) Kevin, 

I followed your instructions and copied version 1.1.3-rc1 over the installer. 

Nevertheless it does not work.

The download, according to the download bar is completed, but after decompressing appears, Error.

I do not know anymore where the worm is in it. 

Maybe here?

 

The download of the setup exe of the installer is saved here.

C:\Users\Uwe\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\FlyByWire Simulations

 

My location for the MSFS is how Microsoft wanted it.

C:\Users\Uwe\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalCache\Packages\Community

 

This is also listed correctly by the installer under Settings. Actually everything is correct.?!

Furthermore I have the addon linker in use. The community folder I have with a few exceptions (Addons from FSDreamTeam) swapped out to a separate SSD (F).

This worked before the version change of the installer to 1.11 smoothly.

 

I am now at a loss.

Best regards, Uwe

 

ich bin Deiner Anweisung gefolgt und habe die Version 1.1.3-rc1 über den Installer drüber kopiert. 

Dennoch klappt es nicht.

Der Download, laut Download-Balken wird zwar vollzogen, aber nach dem Decompressing erscheint, Error….

Ich weiß nicht mehr, wo da der Wurm drin ist. 

Vielleicht hier?

Der Download der Setup-exe des Installers wird hier gespeichert.

C:\Users\Uwe\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\FlyByWire Simulations

 

Mein Speicherort für den MSFS ist der, wie Microsoft es wünschte.

C:\Users\Uwe\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalCache\Packages\Community

 

Dies wird vom Installer auch unter Settings richtig aufgeführt.

eigentlich doch alles richtig

Des Weiteren habe ich den Addon-Linker im Einsatz. Den Community-Ordner habe ich bis auf wenige Ausnahmen (Addons von FSDreamTeam) auf eine separate SSD (F) ausgelagert.

Das funktionierte vor dem Versionswechsel des Installers auf 1.11 reibungslos. 

Natürlich kann ich immer noch den Direkt Download, z.B. Dev-Version von der „Flybywire-Seite“ durchführen.

 

Ich bin jezt ratlos.

Viele Grüße, Uwe aus Bergkamen, bei Dortmund

 

Von: Kevin Diehl ***@***.***> 
Gesendet: Freitag, 26. März 2021 18:47
An: flybywiresim/installer ***@***.***>
Cc: CaptainUwe27 ***@***.***>; Mention ***@***.***>
Betreff: Re: [flybywiresim/installer] Installer does not perform an update, (#193)

 

Hi Uwe,

you are right, I am from Germany. Due to the international community I will answer in English and German (way more below).

Have you tried to install the official installer only or did you used the provided installer from [(https://github.com//issues/179 <https://github.com/flybywiresim/installer/issues/179> #issuecomment-807380531)] ?
There seem to be some problems with the "old" (official) installer.

Please install the Version 1.1.3-rc1 and try again to download the plane.
Maybe you will have to edit the path to your community folder in the settings.

If this will not work maybe you have an Discord Username for us, so we won't abuse Github as a forum? Or maybe you can contact me directly here (I am new to Github and don't know how to send private messages).

German:
Bitte versuche aus dem oben genannten Link mal die Vorabversion des neuen Installers zu installieren. Das ist eine noch nicht veröffentlichte Version, bei der die Probleme aus dem offiziellen Installer gelöst wurden. Die Version ist Version 1.1.3-rc1. Du brauchst den alten Installer nicht deinstallieren. Einfach den neuen "drüberbügeln" und testen. Eventuell musst du noch den Pfad zum Community Ordner richtig abändern.

Falls das nicht klappt, sollten wir schauen, dass wir Github nicht als Forum missbrauchen und uns für alles Weitere im Discord austauschen. Oder du kontaktierst mich hier über eine Privatnachricht (falls es das gibt. Bin selbst noch neu hier und habe eine solche Funktion noch nicht gefunden.)

Best regards / Grüße
Kevin

**Comment by CaptainUwe27** [comment] 2021-03-26 19:05
Hi Kevin,

 

ich habe den Fehler gefunden. Hurra.

Und zwar (obwohl vorher alles gelöscht (Flybywire) wurde, hatte sich da etwas eingenistet, was da eigentlich nicht mehr sein sollte.

Und zwar ist im MSFS Hauptordner (C-Partition) …Community ein Eintrag verlinkt (Addon-Linker) zur F-Partition vorhanden gewesen, der wie folgt lautet: flybywire-aircraft-a320-neo.

Obwohl die Verlinkung angezeigt wird, ist dieser Eintrag nirgends auf „F“ zu finden.

 

Löschen kann ich ihn in „C“ auch nicht, also habe ich vor flybywire…- fault gesetzt.

Danach den Download über den Installer nochmal probiert und jetzt hat alles einwandfrei geklappt.

(Nadel im Heuhaufen)

Nun ja, ich bin froh, dass ich in dieser Hinsicht weitergekommen bin. 

Für Deine Bemühungen bin ich Dir sehr dankbar.

 

Viele Grüße, Uwe 

 

I have found the error. Hooray.

Namely (although everything was deleted before (Flybywire), something had nested there, which should not be there anymore.

Namely, in the MSFS main folder (C-partition) ...Community an entry linked (addon linker) to the F-partition was present, which reads as follows: flybywire-aircraft-a320-neo.

Although the linking is displayed, this entry is nowhere to be found on "F".

 

I can't delete it in "C" either, so I put...- fault in front of flybywire.

After that I tried the download via the installer again and now everything worked fine.

(needle in a haystack)

Well, I am glad that I have made some progress in this respect. 

I am very grateful for your efforts.

 

Many greetings, Uwe 

 

 

 

 

 

Von: Kevin Diehl ***@***.***> 
Gesendet: Freitag, 26. März 2021 18:47
An: flybywiresim/installer ***@***.***>
Cc: CaptainUwe27 ***@***.***>; Mention ***@***.***>
Betreff: Re: [flybywiresim/installer] Installer does not perform an update, (#193)

 

Hi Uwe,

you are right, I am from Germany. Due to the international community I will answer in English and German (way more below).

Have you tried to install the official installer only or did you used the provided installer from [(https://github.com//issues/179 <https://github.com/flybywiresim/installer/issues/179> #issuecomment-807380531)] ?
There seem to be some problems with the "old" (official) installer.

Please install the Version 1.1.3-rc1 and try again to download the plane.
Maybe you will have to edit the path to your community folder in the settings.

If this will not work maybe you have an Discord Username for us, so we won't abuse Github as a forum? Or maybe you can contact me directly here (I am new to Github and don't know how to send private messages).

German:
Bitte versuche aus dem oben genannten Link mal die Vorabversion des neuen Installers zu installieren. Das ist eine noch nicht veröffentlichte Version, bei der die Probleme aus dem offiziellen Installer gelöst wurden. Die Version ist Version 1.1.3-rc1. Du brauchst den alten Installer nicht deinstallieren. Einfach den neuen "drüberbügeln" und testen. Eventuell musst du noch den Pfad zum Community Ordner richtig abändern.

Falls das nicht klappt, sollten wir schauen, dass wir Github nicht als Forum missbrauchen und uns für alles Weitere im Discord austauschen. Oder du kontaktierst mich hier über eine Privatnachricht (falls es das gibt. Bin selbst noch neu hier und habe eine solche Funktion noch nicht gefunden.)

Best regards / Grüße
Kevin

**Comment by FoxtrotSierra6829** [comment] 2021-03-26 22:03
Please [redownload the update for v1.1.3](https://github.com/flybywiresim/installer/releases/download/v1.1.3/setup.exe) manually, as you won't get this one automatically, because you are already on a 1.1.3-rc version.

Closing as it is resolved now.

**Closed by FoxtrotSierra6829** 2021-03-26 22:03 UTC
Labels: Bug

**Comment by CaptainUwe27** [comment] 2021-03-27 09:58
Hi Florian,

 

thanks for contact me. I had written with Kevin Diehl and at least I found the problem. 

I will change to up to date installer.

Since many days I tried to find the solution, why I can´t update with the flybywire installer.

At least,namely (although everything was deleted before (Flybywire) something had nested there, which should not be there anymore.

Namely, in the MSFS main folder (C-partition) ...Community an entry linked (addon linker) to the F-partition was present, which reads as follows: flybywire-aircraft-a320-neo.

Although the linking is displayed, this entry is nowhere to be found on "F".

 

I can't delete it in "C" either, so I put...- fault in front of path flybywire.

After that I tried the download via the installer again and now everything worked fine.

(needle in a haystack)

Well, I am glad that I have made some progress in this respect. 

I have no idea to write this solution on GitHub, but if you like to do it, you can make it. Or tell me, what I can do.

 

Regards, Uwe (CaptainUwe27)

 

 

 

Von: Florian Scheuner ***@***.***> 
Gesendet: Freitag, 26. März 2021 23:03
An: flybywiresim/installer ***@***.***>
Cc: CaptainUwe27 ***@***.***>; Mention ***@***.***>
Betreff: Re: [flybywiresim/installer] Installer does not perform an update, (#193)

 

Please  <https://github.com/flybywiresim/installer/releases/download/v1.1.3/setup.exe> redownload the update for v1.1.3 manually, as you won't get this one automatically, because you are already on a 1.1.3-rc version.

Closing as it is resolved now.
