### ISSUE TITLE
[BUG] Installer fail after MSFS reinstall and directory change

### ISSUE THREAD

**Issue by katana2000** [flybywiresim/installer#269] opened 2021-07-09 07:21 UTC
**Installer Version**
unknown (fresh download)
**Describe the bug**

After Uninstall and reinstall of MSFS in another directory than before the FBW-Installer fails to start and shows the attached error message. Directory "F:\MSFS" was old and does no longer exist, "C:\MSFS" is current installation directory.
Remove and re-installation of the fbw-installer did have no effect. 
**To Reproduce**

1.
2.
3.

**Expected behavior**

**Additional context**

Discord username (if different from GitHub):

![installer_err](https://user-images.githubusercontent.com/87168103/125038984-51619d00-e096-11eb-8830-ee98e8961074.JPG)

**Comment by FoxtrotSierra6829** [comment] 2021-07-09 13:54
duplicate of #258

**Closed by FoxtrotSierra6829** 2021-07-09 13:54 UTC
Labels: Bug
