### ISSUE TITLE
[BUG] Uses over 59gb of ram

### ISSUE THREAD

**Issue by hi1213345446231** [flybywiresim/installer#203] opened 2021-03-28 14:35 UTC
**Installer Version**
1.1.3
**Describe the bug**
Uses over 50gb of ram
![97721EDA-D2FB-491E-9A89-A473887F761D](https://user-images.githubusercontent.com/42178751/112756032-2e294b00-8fdb-11eb-8618-b2f9187b785f.png)

**To Reproduce**

1.probably in background
2.used over 50gb of tam
3.

**Expected behavior**

Not use 50gb of ram

**Additional context**

Discord username (if different from GitHub):

**Comment by FoxtrotSierra6829** [comment] 2021-03-28 17:09
Duplicate of #106

**Closed by FoxtrotSierra6829** 2021-03-28 17:09 UTC
Labels: Bug
