### ISSUE TITLE
[BUG] Currently installed version not detected

### ISSUE THREAD

**Issue by MisterChocker** [flybywiresim/installer#103] opened 2021-01-15 08:53 UTC
**Installer Version**
https://github.com/flybywiresim/installer/commit/666043ac22178b7b1b4f3c0c3e07b0bbcfb6bf76

**Describe the bug**

I've installed the experimental fbw version with v1rc4.
It used to say "Update" as the version was updated, but now it's showing me "Switch version" instead of "Update".

**To Reproduce**

I've no clue on how to reproduce.
(I've now deleted the current installation and installed the same version, now reads "Installed", waiting for update on cfbw version)

**Expected behavior**

To show "Update" for the currently installed version.

**Additional context**

Discord username (if different from GitHub):

**Comment by FoxtrotSierra6829** [comment] 2021-01-26 21:20
Has this ever occured again since then? I'm not sure if it could just be the fact, that you had the FBW version installed as 'FBW' before and then as it got changed to 'Custom FBW', the name property did not match anymore. I'm pretty sure it compares the versions based on exactly that name.

**Comment by MisterChocker** [comment] 2021-01-26 22:01
@FoxtrotSierra6829 I haven't tested since, nor used the installer.
Since I am heavy into developing I am always rolling with git and building it myself.

**Comment by FoxtrotSierra6829** [comment] 2021-01-26 22:44
> 
> 
> Has this ever occured again since then? I'm not sure if it could just be the fact, that you had the FBW version installed as 'FBW' before and then as it got changed to 'Custom FBW', the name property did not match anymore. I'm pretty sure it compares the versions based on exactly that name.

@ZigTag could this be the cause? If so, I think we can disregard it and close the issue.

**Comment by MisterChocker** [comment] 2021-01-26 22:51
maybe

**Comment by ZigTag** [comment] 2021-01-27 04:30
> > 
> > 
> > Has this ever occured again since then? I'm not sure if it could just be the fact, that you had the FBW version installed as 'FBW' before and then as it got changed to 'Custom FBW', the name property did not match anymore. I'm pretty sure it compares the versions based on exactly that name.
> 
> @ZigTag could this be the cause? If so, I think we can disregard it and close the issue.

I doubt it but it happened only after I made that change so probably, I've never had the problem afterwards

**Comment by ZigTag** [comment] 2021-01-27 04:31
Closing due to it being a one off bug

**Closed** 2021-01-27 04:30 UTC
Labels: Bug
