### ISSUE TITLE
[BUG] Unable to access installer

### ISSUE THREAD

**Issue by lekkerjonty** [flybywiresim/installer#268] opened 2021-07-04 16:35 UTC
**Installer Version**

**Describe the bug**
When trying to access the installer I get an error message 
![image](https://user-images.githubusercontent.com/76077409/124392523-063e3780-dcee-11eb-9f83-106415a4ef97.png)
My community folder has moved, but I do not know how to rectify this issue.
**To Reproduce**

1.I loaded up the installer after moving the community folder.
2. Error message appears
3.

**Expected behavior**

Error message shouldn't appear

**Additional context**

Discord username (if different from GitHub):

**Comment by FoxtrotSierra6829** [comment] 2021-07-04 16:37
duplicate of #258

**Closed by FoxtrotSierra6829** 2021-07-04 16:37 UTC
Labels: Bug
