### ISSUE TITLE
UNABLE TO RUN INSTALLER

### ISSUE THREAD

**Issue by thenicholashenry** [flybywiresim/installer#262] opened 2021-06-21 01:07 UTC
**1.2.0**

I tried moving my MSFS Official and Community folder to a different drive (:D\) from (:C\) and now when I launch the installer, it gives me an error.
![image](https://user-images.githubusercontent.com/72879832/122694280-dfbacf80-d20a-11eb-95d2-c677544dcdc4.png)

![image](https://user-images.githubusercontent.com/72879832/122694305-ef3a1880-d20a-11eb-937f-0633cbaa8f5e.png)

![image](https://user-images.githubusercontent.com/72879832/122694317-f7925380-d20a-11eb-89a9-5fa53d5dcae6.png)

**To Reproduce**
Change MSFS folder and userconfig path to a different drive and launch. 

**Expected behavior**
It will give an error posted in the screenshot above.

**Additional context**

Discord username: xNick_O#5019:

**Comment by FoxtrotSierra6829** [comment] 2021-06-21 14:27
duplicate of #258

**Closed by FoxtrotSierra6829** 2021-06-21 14:27 UTC
Labels: Bug
