### ISSUE TITLE
Notifications when a new update is available

### ISSUE THREAD

**Issue by EuanM199** [flybywiresim/installer#392] opened 2022-07-17 20:24 UTC
### Installer Version

V3.1.0

### Description

I would like to see a notification system be added so that when a new update is pushed to stable, development, or experimental ether a notification could be sent through windows, or when you open up the simulator it alerts you to it, it could also be toggleable for people that would not want to be notified.

this i think would help both newer and more experienced FBW users as I know for a fact quite a lot of us have missed an update or 10 on experimental since they are pushed so often, it could also possibly lessen the number of support questions from users using versions months old.

### Discord Username (optional)

Euan#7980

**Comment by FoxtrotSierra6829** [comment] 2022-07-17 20:45
duplicate of #72

**Closed by FoxtrotSierra6829** 2022-07-17 20:45 UTC
