### ISSUE TITLE
[BUG] Copying to temp dir fails due to an encrypted community dir

### ISSUE THREAD

**Issue by belima** [flybywiresim/installer#179] opened 2021-03-22 01:38 UTC
**Installer Version**
1.1.1

**Describe the bug**
Can't update Aircraft. When clicking the Update button I get a "Preparing Update" message and nothing happens. Cancel button doesn't work either. Only way to restart is closing and reopening the software. After manually deleting aircraft folder inside Community folder and clicking the Install button I get the "Downloading Full Module" msg and everything works as expected.

**To Reproduce**
1. Open the installer with an outdated aircraft installed.
2. Click the "Update" Button

**Expected behavior**
Aircraft should be updated.

**Comment by FoxtrotSierra6829** [comment] 2021-03-22 17:27
Can you check, if you're able to copy the complete Community folder or if it's got a lock on the icon? It seems this is an issue with write protection for some users.

**Comment by belima** [comment] 2021-03-22 17:59
I can't copy the Community folder nor any of the folders inside. There's no lock on the icon, but I believe files are encrypted since filenames are green, right? I have no issue deleting the files though.

**Comment by FoxtrotSierra6829** [comment] 2021-03-22 18:08
Yeah that seems to be exactly the issue for quite some users. You can try if it helps any to make these unencrypted by Using `Properties/Advanced` and uncheck `encrypt files to secure data`. If that didn't help, you can try to to gain access by the context menu, if there is an item called `File Ownership` or else, by `Properties/Security/Advanced`

**Comment by belima** [comment] 2021-03-22 18:29
No success, I think :(

When trying to make files unencrypted I get "Error Applying Attributes". Weird thing is I checked `Properties/Security/Advanced` and I have both Effective Access and ownership of the files.

**Comment by FoxtrotSierra6829** [comment] 2021-03-22 18:51
If the error still occurs, and you have a second drive or a second partition, please try if moving your MSFS installation in your Windows Settings/Apps does help.

![grafik](https://user-images.githubusercontent.com/50082450/112042505-dfe1fb00-8b47-11eb-93c7-415b7636b274.png)

**Comment by FoxtrotSierra6829** [comment] 2021-03-22 22:02
Please download [this version of the FlyByWire Installer](https://github.com/flybywiresim/installer/releases/download/vmaster/setup.exe) which contains additional logging capabilities. Open the dev tools by `CTRL+F12`, run the installation process, and after it failed, right click on any item in the console at the bottom right, and hit `save as` to save the log of this. Please send the log to us then. That would help us a lot to better identify the problem, thanks.

**Comment by AdamNZ** [comment] 2021-03-22 23:43
I'm having problems as well. I've tried all sorts of strategies - including installing the STABLE version (fresh) - which installs fine - then doing a "Switch" to the DEV version. No go.

As a test, I tried the Custom FBW version. That one installed fine - so there's definitely something shonky about the DEV version.

It's not a permissions problem, IMHO, as I've been using the DEV version from day one - and I have my addons *outside* my Community folder, but activated with symlinks, using the addons linker.

**Comment by FoxtrotSierra6829** [comment] 2021-03-23 00:20
@AdamNZ yeah using addons linker you should not have permission problems 99%. Weird thing is just previous reports of being unable to switch to dev only were about getting "failed to install". Can you follow the above and send us a log?

**Comment by belima** [comment] 2021-03-23 01:26
Just downloaded the version you asked and tried updating the aircraft. No need to wait for 30 seconds, error happened as soon as I clicked the `Update` button.  

[fbwlog.txt](https://github.com/flybywiresim/installer/files/6186240/fbwlog.txt)

**Comment by nistei** [comment] 2021-03-23 01:35
```
index.html:1 Uncaught (in promise) Error: UNKNOWN: unknown error, copyfile 'D:\Users\[REDACTED]\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalCache\Packages\Community\flybywire-aircraft-a320-neo\zh-CN.locPak' -> 'D:\Users\[REDACTED]\AppData\Local\Temp\flybywire_installer\zh-CN.locPak'
```

**Comment by belima** [comment] 2021-03-23 02:45
> Just downloaded the version you asked and tried updating the aircraft. No need to wait for 30 seconds, error happened as soon as I clicked the `Update` button.
> 
> [fbwlog.txt](https://github.com/flybywiresim/installer/files/6186240/fbwlog.txt)

Now I can't even do a Full Install. File downloads, but doesn't get installed. Log Attached ;)


[fbwlog_clean_install_fail.txt](https://github.com/flybywiresim/installer/files/6186543/fbwlog_clean_install_fail.txt)

**Comment by nistei** [comment] 2021-03-23 03:47
> > Just downloaded the version you asked and tried updating the aircraft. No need to wait for 30 seconds, error happened as soon as I clicked the `Update` button.
> > [fbwlog.txt](https://github.com/flybywiresim/installer/files/6186240/fbwlog.txt)
> 
> Now I can't even do a Full Install. File downloads, but doesn't get installed. Log Attached ;)
> 
> [fbwlog_clean_install_fail.txt](https://github.com/flybywiresim/installer/files/6186543/fbwlog_clean_install_fail.txt)

We've traced the issue back to our CDN provider and have resolved it. All downloads should be working now.

**Comment by AdamNZ** [comment] 2021-03-23 08:23
I'm having problems as well. I've tried all sorts of strategies - including installing the STABLE version (fresh) - which installs fine - then doing a "Switch" to the DEV version. No go.

As a test, I tried the Custom FBW version. That one installed fine - so there's definitely something shonky about the DEV version.

It's not a permissions problem, IMHO, as I've been using the DEV version from day one - and I have my addons *outside* my Community folder, but activated with symlinks, using the addons linker.

**Comment by AdamNZ** [comment] 2021-03-23 08:25
Update: I've been out all day, but tried again just now. All appears to have been fixed, so a HUGE shout out to everyone contributing their own spare time to this fantastic project - *THANK YOU*!!

**Comment by FoxtrotSierra6829** [comment] 2021-03-23 10:41
@belima do you still have the issues after a fresh installation now? Will be closing this otherwise.

**Comment by belima** [comment] 2021-03-23 19:41
Hey, sorry for the delay. Different time zones I guess lol

Full downloads work again! Is the Update issue also supposed to be fixed with this correction? I'll try it out after the next master commit.

**Comment by FoxtrotSierra6829** [comment] 2021-03-23 20:09
We don't know, since we didn't get any other reports like this since the fix, but it could be.

**Comment by admon67** [comment] 2021-03-25 07:48
Hey volks - I have the same issue!
My steps:
- deinstalled the mod installer
- delete all folders and files from the MSFS community folder
- reboot the system
- install the dev installer (linked above)
- install the A32NX dev version - download full module and initial installation works fine
- following updates of the dev version will be failed with this error output (ctrl+F12):

> index.html:1 Uncaught (in promise) Error: UNKNOWN: unknown error, copyfile 'C:\Users\[REDACTED]\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalCache\Packages\Community\flybywire-aircraft-a320-neo\zh-CN.locPak' -> 'C:\Users\[REDACTED]\AppData\Local\Temp\flybywire_installer\zh-CN.locPak'

- if I trie to copy the file manualy, I get this system message: "Do you want to copy this file without encryption?" 

Is that the reason of this issue?

Thanks a lot!

**Comment by jartweb** [comment] 2021-03-25 08:13
Echoing the experience of admon67

After managing to get a download of Development version to work yesterday, this morning, when trying to perform an update to a81ec5b, the previous problem seems to still be present. Stuck on 'preparing update' and the debug output shows that the problem is on trying to copy the zh-CN.locPak file to a temporary folder on the C drive from the main install which is on D. If I manually try to copy the file, the dialog box warns that I am copying to a non-encrypted location. If I delete this file and re-run the installer, the same error occurs with the ru-RU.locPak file. If I copy all these files across manually to the temp folder, they get deleted when I re-run the installer and the same error occurs. If I get file properties on these files and head to the Advanced items I can see that the 'Encrypt file contents' box is checked. If I try to uncheck this and Apply, I get a 'Parameter incorrect' error and the file remains encrypted. AFAIK, I am listed as the file owner. Using installer 1.1.2-dev. FS2020 is installed to D due to small size of C drive.

Have had no installer problems until this week. 

[dev-update-req-toa81ec5b.txt](https://github.com/flybywiresim/installer/files/6202968/dev-update-req-toa81ec5b.txt)

**Comment by FoxtrotSierra6829** [comment] 2021-03-25 11:17
Okay, thank you all for the feedback. It seems this is now only caught by Community folders to which the Installer has limited write access, either because of encryption or because of a wrong ownership leading to write protection for the user. This doesn't seem to be fixable on our side though, and the possible workarounds that I can imagine are all not very good. I can suggest trying two things:
- Either reinstall MSFS entirely and choose a different install folder
- or move it:
		In `%userprofile%\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalCache` you will find a file called `UserCfg.opt`. It's last line is pointing to the current `InstalledPackagesPath`. Move this folder to a different location and change the line to the new one.

**Comment by admon67** [comment] 2021-03-25 11:25
Thanks for your feedback, Foxtrot!
A question - why the issue occurse just after the installer update?
Before performing the fbw-installer update all works fine under the same conditions. Hmm ...

**Comment by FoxtrotSierra6829** [comment] 2021-03-25 11:34
@admon67 We weren't copying the folder before, as we always reinstalled everything in the past. Now with the modular installer, it is required to copy the existing parts, to exchange updated ones properly without failures.

**Comment by admon67** [comment] 2021-03-25 12:29
@FoxtrotSierra6829 - ok I understood!

I've found following on serverbrain.org:

> The COPY command used in a command console has been modified to support encryption. You can use the /D switch to copy an encrypted file to a non-EFS capable volume, but the file loses its encryption. Following is an example:
> 
> COPY /D sourcefile destinationfile
> 
> The XCOPY command also supports copying to non-EFS-capable volumes. XCOPY, however, uses the /G switch for this functionality. The syntax is similar to that for the COPY command.
> 
> If you rename a folder or file, the encryption attribute is unaffected. Therefore, you can rename an encrypted folder or file in place, and it remains encrypted. In addition, you can rename a folder or file to a different location (essentially a move operation), and the folder or file remains encrypted, even if it's renamed to an NTFS folder that is not encrypted.

Is there an option to use this command switchs for the copy action?

(sorry for my bad english)

**Comment by FoxtrotSierra6829** [comment] 2021-03-25 13:23
@admon67 sadly no, as we are using commands that are completely unrelated to windows command-line. I will look if there are any other possibilities for our commands, but I don't have high hopes on that.

**Comment by admon67** [comment] 2021-03-25 14:57
Hmm .... perhaps it is a workaround to encrypt the Temp Folder like the source folder... (C:\Users[REDACTED]\AppData\Local\Temp\flybywire_installer)
Is the folder flybywire_installer persistent or will it be deleted after the update process?
I will test it!
Thx!

**Comment by nistei** [comment] 2021-03-25 15:26
The copy to the temporary directory is only done as a safety measure to have something to fall back in case of issues during the update or the user cancels a download.
I will add an in-place option for the installer which will make it work in the community directory. The downside of this is that if a module update fails the addon is broken.

Unless...
@admon67 Can you check if you can copy the a32nx within the community directory? This would allow us to use the community directory as a temporary directory as a fallback for when the Windows temp dir isn't working.

**Comment by admon67** [comment] 2021-03-25 17:46
> @admon67 Can you check if you can copy the a32nx within the community directory? This would allow us to use the community directory as a temporary directory as a fallback for when the Windows temp dir isn't working.

Hi Niklas - yes it works.
If I create a new folder inside of the community folder this one will be encrypted automatically and I can copy all files and subfolders from dir flybywire-aircraft-a320-neo to the new one without confirmations!

thx for your support!

**Comment by jartweb** [comment] 2021-03-25 18:14
Confirmed from me too!

I can create a folder \Community\temporary and can copy files from \Community\flybywire-aircraft-a320-neo to that new folder and the copied files remain encrypted and there is no file copy warning.

Thanks for helping out on this!

[For info I do not recall doing anything strange during the install of FS2020 - I had bought a much bigger drive for D and wanted to keep C a bit smaller, so performed the install to D. Not sure why it then decided to encrypt this location].

**Comment by nistei** [comment] 2021-03-25 19:58
@jartweb @admon67 Can you test if this version works for you? I cannot test it myself since I am on the Steam version.
Please send me the logs again using `Ctrl+F12`, even if the install is working.

Direct download: https://github.com/flybywiresim/installer/releases/download/v1.1.3-rc1/setup.exe
Release page: https://github.com/flybywiresim/installer/releases/tag/v1.1.3-rc1

**Comment by jartweb** [comment] 2021-03-26 08:27
@nistei 
Yes!!!

Just tested v 1.1.3-rc1 of the installer. Checked the settings: Disable Version Warnings and Use CDN (Faster Downloads) both ticked. Selected Development version (already installed) - Upgrade button became active. Pushed it. Slightly worrying pause for a few seconds with 'Preparing update' displayed ....so I opened the debug menu - seemed OK, nothing showing in red font ..... then action  ! - couple of packages were downloaded in a few seconds and a few seconds later the install was complete (Windows notification popped up too). Quit the installer. Re-started. Re-selected Development - shows as Installed.

So as far as I can see this used the new downloader to only update the necessary components and however it was doing the file copy behind the scenes has worked for me. 

I'll check out the new version and then look in more detail at the logs during the next patch (rumour of major update on Dev channel coming soon) and report anything else. But for now, this seems to be A-OK.

Many thanks for saving what's left of my hair and my bandwidth!

**Comment by nistei** [comment] 2021-03-26 15:12
Fixed in #191

**Closed by nistei** 2021-03-26 15:12 UTC
Labels: Bug, Critical

**Comment by Kamegohan** [comment] 2021-03-26 16:19
Coming from #193. 

Installer V1.1.3-rc1 was installed and tested. 

Installer found an updated "Dev-A32NX". Downloading and installing the updated files took about 2 seconds (against ~10-15 seconds for former updates). During copying the log there was a second (plane) update availabe, which was getting installed the same smooth way as the first one.

As I am not 100% sure where to start in the log you will get the whole thing here, hopefully in a readable formatting. I am very new to this, so if I can provide data in a better way just tell me. 

<details>
<summary>Installer console log</summary>

- Currently installed {modules: Array(8), base: {…}, fullHash: "1ca3c9c4c9743f827bbbdbe26abf832df5d3622bc0e38500e7…232b18c5c515f0a600c048de21ed76da3a5503fe2907a5cdf", source: "https://cdn.flybywiresim.com/addons/a32nx/master"}base: {hash: "18e2f8be01f800d4a85ed38e65ae5bc9d5ab1940fb3f619ee8…05d72b45e3c812654c83c7adf040ece69d97e5ef8a2e075df", files: Array(33)}fullHash: "1ca3c9c4c9743f827bbbdbe26abf832df5d3622bc0e38500e7beb3bbb87554cb9f3f1e43d66284d232b18c5c515f0a600c048de21ed76da3a5503fe2907a5cdf"modules: (8) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]source: "https://cdn.flybywiresim.com/addons/a32nx/master"__proto__: Object

- index.tsx:107 Currently installed {name: "Development", key: "a32nx-dev", url: "https://cdn.flybywiresim.com/addons/a32nx/master", description: {…}, isExperimental: false, …}

- index.tsx:202 Checking install status

- index.tsx:184 Checking for git install

- index.tsx:192 Is not git repo

- index.esm.js:5831 Downloading module info from https://cdn.flybywiresim.com/addons/a32nx/master/modules.json

- index.tsx:104 Currently installed {modules: Array(8), base: {…}, fullHash: "1ca3c9c4c9743f827bbbdbe26abf832df5d3622bc0e38500e7…232b18c5c515f0a600c048de21ed76da3a5503fe2907a5cdf", source: "https://cdn.flybywiresim.com/addons/a32nx/master"}

- index.tsx:107 Currently installed {name: "Development", key: "a32nx-dev", url: "https://cdn.flybywiresim.com/addons/a32nx/master", description: {…}, isExperimental: false, …}

- index.tsx:202 Checking install status

- index.tsx:184 Checking for git install

- index.tsx:192 Is not git repo

- index.esm.js:5831 Downloading module info from https://cdn.flybywiresim.com/addons/a32nx/master/modules.json

- index.tsx:104 Currently installed {modules: Array(8), base: {…}, fullHash: "1ca3c9c4c9743f827bbbdbe26abf832df5d3622bc0e38500e7…232b18c5c515f0a600c048de21ed76da3a5503fe2907a5cdf", source: "https://cdn.flybywiresim.com/addons/a32nx/master"}

- index.tsx:107 Currently installed {name: "Development", key: "a32nx-dev", url: "https://cdn.flybywiresim.com/addons/a32nx/master", description: {…}, isExperimental: false, …}

- index.esm.js:5848 Existing install {modules: Array(8), base: {…}, fullHash: "1ca3c9c4c9743f827bbbdbe26abf832df5d3622bc0e38500e7…232b18c5c515f0a600c048de21ed76da3a5503fe2907a5cdf", source: "https://cdn.flybywiresim.com/addons/a32nx/master"}

- index.esm.js:5859 Base CRC does not match. Update needed.

- index.tsx:218 Update info {needsUpdate: true, isFreshInstall: false, baseChanged: true, distributionManifest: {…}, addedModules: Array(0), …}

- index.esm.js:5848 Existing install {modules: Array(8), base: {…}, fullHash: "1ca3c9c4c9743f827bbbdbe26abf832df5d3622bc0e38500e7…232b18c5c515f0a600c048de21ed76da3a5503fe2907a5cdf", source: "https://cdn.flybywiresim.com/addons/a32nx/master"}

- index.esm.js:5859 Base CRC does not match. Update needed.

- index.tsx:218 Update info {needsUpdate: true, isFreshInstall: false, baseChanged: true, distributionManifest: {…}, addedModules: Array(0), …}

- index.tsx:255 Installing {name: "Development", key: "a32nx-dev", url: "https://cdn.flybywiresim.com/addons/a32nx/master", description: {…}, isExperimental: false, …}

- index.tsx:256 Installing into C:\Flugsimulator\Community\flybywire-aircraft-a320-neo using temp dir C:\Flugsimulator\Community\flybywire_current_install_170

- index.tsx:265 Checking for existing install

- index.tsx:268 Found existing install at C:\Flugsimulator\Community\flybywire-aircraft-a320-neo

- index.tsx:269 Copying existing install to C:\Flugsimulator\Community\flybywire_current_install_170

- index.tsx:271 Finished copying

- index.tsx:284 Starting fragmenter download for URL https://cdn.flybywiresim.com/addons/a32nx/master

- index.esm.js:6020 Finding modules to update

- index.esm.js:5831 Downloading module info from https://cdn.flybywiresim.com/addons/a32nx/master/modules.json

- index.esm.js:5848 Existing install {modules: Array(8), base: {…}, fullHash: "1ca3c9c4c9743f827bbbdbe26abf832df5d3622bc0e38500e7…232b18c5c515f0a600c048de21ed76da3a5503fe2907a5cdf", source: "https://cdn.flybywiresim.com/addons/a32nx/master"}

- index.esm.js:5859 Base CRC does not match. Update needed.

- index.esm.js:6024 Update info {needsUpdate: true, isFreshInstall: false, baseChanged: true, distributionManifest: {…}, addedModules: Array(0), …}

- index.esm.js:6041 Found existing manifest {modules: Array(8), base: {…}, fullHash: "1ca3c9c4c9743f827bbbdbe26abf832df5d3622bc0e38500e7…232b18c5c515f0a600c048de21ed76da3a5503fe2907a5cdf", source: "https://cdn.flybywiresim.com/addons/a32nx/master"}

- index.esm.js:6060 Updating base files

- index.esm.js:5907 Downloading file base.zip

- index.esm.js:5912 Downloading from https://cdn.flybywiresim.com/addons/a32nx/master/base.zip

- index.esm.js:5947 Finished downloading file base.zip

- index.esm.js:5891 Validating file CRC

- index.esm.js:5893 CRC should be ebd4fa2d2bffdbf96ef790fa775702994966a8807be075b482b0f734eb0a571442eaef1e45a390dc38e9c72fa2ae080ff20eed134efd6deb1537f9a6271e5498 and is ebd4fa2d2bffdbf96ef790fa775702994966a8807be075b482b0f734eb0a571442eaef1e45a390dc38e9c72fa2ae080ff20eed134efd6deb1537f9a6271e5498

- index.esm.js:5969 CRC was correct

- index.esm.js:5973 Extracting ZIP to C:\Flugsimulator\Community\flybywire_current_install_170

- index.esm.js:5978 Finished extracting ZIP to C:\Flugsimulator\Community\flybywire_current_install_170

- index.esm.js:6079 Removing changed and removed modules (2) [{…}, {…}]

- index.esm.js:6081 Removing module {name: "ModelBehaviorDefs", sourceDir: "./ModelBehaviorDefs", hash: "74997b063d30c71466e368f637f8eb7b26a9c9270d551b7323…b3f8659ad36983526d70cb4d6514e60e3a24072554e7b412d"}

- index.esm.js:6085 Removed module {name: "ModelBehaviorDefs", sourceDir: "./ModelBehaviorDefs", hash: "74997b063d30c71466e368f637f8eb7b26a9c9270d551b7323…b3f8659ad36983526d70cb4d6514e60e3a24072554e7b412d"}

- index.esm.js:6081 Removing module {name: "Model", sourceDir: "./SimObjects/AirPlanes/Asobo_A320_NEO/model", hash: "f1687d1429e0b14ad51b71b4e928acd51a529980dd33401d45…fa4043b0e5b116a7d8884a7a00ed347c764424973ec96cb23"}

- index.esm.js:6085 Removed module {name: "Model", sourceDir: "./SimObjects/AirPlanes/Asobo_A320_NEO/model", hash: "f1687d1429e0b14ad51b71b4e928acd51a529980dd33401d45…fa4043b0e5b116a7d8884a7a00ed347c764424973ec96cb23"}

- index.esm.js:6097 Installing changed and added modules (2) [{…}, {…}]

- index.esm.js:6104 Installing new module {name: "ModelBehaviorDefs", sourceDir: "./ModelBehaviorDefs", hash: "9df2d09566d32b9a7e9192fd8a5f418259cacb0890f46b6d31…4214b1420db77cd0ef9776b3a7e9a64a8aed0bedebe3ccf53"}

- index.esm.js:5907 Downloading file ModelBehaviorDefs.zip

- index.esm.js:5912 Downloading from https://cdn.flybywiresim.com/addons/a32nx/master/ModelBehaviorDefs.zip

- index.esm.js:5947 Finished downloading file ModelBehaviorDefs.zip

- index.esm.js:5891 Validating file CRC

- index.esm.js:5893 CRC should be 9df2d09566d32b9a7e9192fd8a5f418259cacb0890f46b6d31f5cf664e10c47ede8d1a5a138e8804214b1420db77cd0ef9776b3a7e9a64a8aed0bedebe3ccf53 and is 9df2d09566d32b9a7e9192fd8a5f418259cacb0890f46b6d31f5cf664e10c47ede8d1a5a138e8804214b1420db77cd0ef9776b3a7e9a64a8aed0bedebe3ccf53

- index.esm.js:5969 CRC was correct

- index.esm.js:5973 Extracting ZIP to C:\Flugsimulator\Community\flybywire_current_install_170\ModelBehaviorDefs

- index.esm.js:5978 Finished extracting ZIP to C:\Flugsimulator\Community\flybywire_current_install_170\ModelBehaviorDefs

- index.esm.js:6104 Installing new module {name: "Model", sourceDir: "./SimObjects/AirPlanes/Asobo_A320_NEO/model", hash: "d912fad840c1dae842cd6b179f8a56b1307a61ee248fcc1856…cfa5ad0fd1a42f31af5511dd691a2adffc554d3602a0ae647"}

- index.esm.js:5907 Downloading file Model.zip

- index.esm.js:5912 Downloading from https://cdn.flybywiresim.com/addons/a32nx/master/Model.zip

- index.esm.js:5947 Finished downloading file Model.zip

- index.esm.js:5891 Validating file CRC

- index.esm.js:5893 CRC should be d912fad840c1dae842cd6b179f8a56b1307a61ee248fcc18566b60980012665f47b696a6b170717cfa5ad0fd1a42f31af5511dd691a2adffc554d3602a0ae647 and is d912fad840c1dae842cd6b179f8a56b1307a61ee248fcc18566b60980012665f47b696a6b170717cfa5ad0fd1a42f31af5511dd691a2adffc554d3602a0ae647

- index.esm.js:5969 CRC was correct

- index.esm.js:5973 Extracting ZIP to C:\Flugsimulator\Community\flybywire_current_install_170\SimObjects\AirPlanes\Asobo_A320_NEO\model

- index.esm.js:5978 Finished extracting ZIP to C:\Flugsimulator\Community\flybywire_current_install_170\SimObjects\AirPlanes\Asobo_A320_NEO\model

- index.esm.js:6006 Writing install manifest {modules: Array(8), base: {…}, fullHash: "a001566467154c9b1796eb18ee1aeed3ee1b17fe93dab81aaa…3cee5b23e43a64377f2ab0c8340e5e6262195e7496d3d5933", source: "https://cdn.flybywiresim.com/addons/a32nx/master"} to C:\Flugsimulator\Community\flybywire_current_install_170\install.json

- index.esm.js:6008 Finished writing install manifest {modules: Array(8), base: {…}, fullHash: "a001566467154c9b1796eb18ee1aeed3ee1b17fe93dab81aaa…3cee5b23e43a64377f2ab0c8340e5e6262195e7496d3d5933", source: "https://cdn.flybywiresim.com/addons/a32nx/master"} to C:\Flugsimulator\Community\flybywire_current_install_170\install.json

- index.tsx:300 Fragmenter download finished for URL https://cdn.flybywiresim.com/addons/a32nx/master

- index.tsx:305 Removing previous install

- index.tsx:308 Copying files from C:\Flugsimulator\Community\flybywire_current_install_170 to C:\Flugsimulator\Community\flybywire-aircraft-a320-neo

- index.tsx:310 Finished copying files from C:\Flugsimulator\Community\flybywire_current_install_170 to C:\Flugsimulator\Community\flybywire-aircraft-a320-neo

- index.tsx:313 Removing installs existing under alternative names

- index.tsx:322 Finished removing installs existing under alternative names

- index.tsx:380 Requesting notification

- index.tsx:331 Finished download {changed: true, manifest: {…}}

- index.tsx:346 Cleaning up temporary directory C:\Flugsimulator\Community\flybywire_current_install_170

- index.tsx:365 Download and install complete

- index.tsx:382 Showing notification

</details>

Best regards,
Kamegohan

**Comment by admon67** [comment] 2021-03-26 16:41
> Can you test if this version works for you? I

Hi Niklas,
thanks for your work!

I've tested the installer v1.1.3-rc3 and it works!
The "preparing update" takes round about 6 - 8 sec - then the update installation is starting!
Well done!

Here is the Log:

[fbwinstaller_v1.1.3-rc3_log.txt](https://github.com/flybywiresim/installer/files/6213166/fbwinstaller_v1.1.3-rc3_log.txt)

**Comment by belima** [comment] 2021-03-26 16:43
Installer V1.1.3-rc1 works for me!

Update process completed successfully, despite taking kinda long to copy files in and out copy folder (around 1,5 minutes each time files were copied)

[fbwlog.txt](https://github.com/flybywiresim/installer/files/6213207/fbwlog.txt)
