### ISSUE TITLE
Installer constantly freezes at the very end if doing an update. 

### ISSUE THREAD

**Issue by Annolago** [flybywiresim/installer#266] opened 2021-07-02 10:05 UTC
**Installer Version 1.2.0**

**Describe the bug**
When I try to run an update using the installer it simply stops at what appears to be the very last step in the upgrade process. 
The installer is displaying "cleaning up" and then simply stops. Moving the mouse curser across the installer shows that the app is frozen and the curser does not react like it normally would by changing into stretch and resize version of the curser. 
Looking at the task manager list simply shows that two instances of the app is running. 
The app cannot be closed like normal programs and have to be terminated. 
However when terminated a new "app" called FlybyWire shows up under background processes (not visible until the main app is killed) but the funny thing is that it is shown as being suspended.
I have tried running the app as both a regular app and in Administrator mode. Makes no difference. 
Now if I remove the FlyByWire install in the Community folder so that the app thinks it is a new install then it works as expected.
However updating that next time there is an update will again make the program hang.

It seems to me that the issue is related to deleting the temp folders and content created during the install.
HOWEVER! When I kill the program I can see the temp folder in my community folder, but (and here comes the puzzling part) if I then start the app again - it will tell me that no upgrade is available and if I then exit it and look in the community folder then the temp install folder is now gone. So apparently the Installer will delete the temp folder at startup.

**To Reproduce**

1. Just start the Installer and the select the development version and perform the upgrade.

**Expected behavior**

That the Installer does the upgrade and then states when it is completed.

**Additional context**

I have naturally tried to reinstall the Installer multiple times, but has not changed the outcome. 
It originally did work, but I am sorry to say that I cannot recall anything specific about why and when it started behaving like this.
The version of Flightsim that I have was purchased from the Microsoft Store - in case that is relevant.

**Comment by FoxtrotSierra6829** [comment] 2021-07-02 15:38
could you send me a log file please? Press `CTRL+F12`, click right on the console (bottom right) and `save as...`, then upload it here

**Comment by Annolago** [comment] 2021-07-03 13:27
How would I do a log file when the installer freezes on my? Will naturally try but think result is given in advance..

**Comment by FoxtrotSierra6829** [comment] 2021-07-03 22:44
Screenshots of the console then maybe?

**Comment by Annolago** [comment] 2021-07-05 12:32
![Installer](https://user-images.githubusercontent.com/75162215/124471165-d437de80-dd9c-11eb-8215-bdccb2390df4.jpg)
So, tried doing the update and it did once again freeze. Here is what I could get from it screen shoot wise. 
Unfortunately the curser is not included in a screen shoot otherwise you would have seen that the curser changes into a double arrow going both left and right. 
Below is the result in my community folder - as you can see it dies before cleaning the temp folder. 
Last time when I tried started FlightSim it could not find the FlyByWire a320, and had to reinstall again. Normally if I just restart the installer it would do the clean up. This may have been a fluke or due to code change - don't know but though you would want to know..
![Community Folder](https://user-images.githubusercontent.com/75162215/124471642-68a24100-dd9d-11eb-8591-8324cb64a0fe.jpg)

**Comment by Annolago** [comment] 2021-07-05 12:32
Forgot - yes, I have also tried without the other stuff in the community folder. Made no difference..

**Comment by FoxtrotSierra6829** [comment] 2021-07-05 13:38
it seems default wise your console is not pinned to the bottom left, so you have to switch the tab to console (next to elements in the bar at the top), then screenshot again.

**Comment by Annolago** [comment] 2021-07-06 09:31
Ok - that is strange. Switched to console and the installer completed...?? Never done that since the issue started and I have not changed anything..
![Installer - Now with Console](https://user-images.githubusercontent.com/75162215/124577374-7b744e80-de4d-11eb-916c-a6d451e50c89.jpg)
I will try to do another update once a new version is out in a day or two..
Sorry about the "redacted" version but hope you understand why..

**Comment by FoxtrotSierra6829** [comment] 2021-07-06 19:00
Hmm, yeah that's weird. I hope the issue is gone, but we'll see if it comes back

**Comment by Annolago** [comment] 2021-07-09 13:35
![Installer with Console Hung](https://user-images.githubusercontent.com/75162215/125085001-69531400-e0ca-11eb-98b7-b209828fe70d.jpg)
So - Tried update again today and it hung as always. The yellow "circle" indicator next to the model selection (between a320 and a380) stopped rotating and again when the mouse cursor is moved across the window it turns into a double arrow pointing both  left and right. 
I have also included a screenshot of the Task Manager - Don't know if that will give you anything, but still here it is
![Task Manager](https://user-images.githubusercontent.com/75162215/125085815-470dc600-e0cb-11eb-9f64-118ca7fead83.jpg)

Hope this helps.. Wish I had more info to pass on.

**Comment by Annolago** [comment] 2021-07-27 09:02
Ok - so an update from my side. It continues to hang when ever I try to install it. If I then restart the app it deletes the temp folder and shows installed status, but not sure that is fully correct but don't know how to test all, unless you want me to give you a number on installed files and folder size - but that would then be for next upgrade cycle..

**Comment by Annolago** [comment] 2021-07-27 09:03
![Installer Hang 27-7-2021](https://user-images.githubusercontent.com/75162215/127127222-217d7e1e-0e4d-4a00-9dbf-9807abc900bc.jpg)

**Comment by Annolago** [comment] 2021-08-03 14:31
OK - even though it seems like no one is reading this any longer I am including this extra info that I found.
When the installer hangs - then the only way to kill it is to open the task manager and end the program. Now doing this some times leaves a background process still running. Now the interesting thing is that it is suspended. You can see for your self here..
The first pictures is the standard view when I open the task manager - that is always the same..

**Comment by Annolago** [comment] 2021-08-03 14:32
![Task Manager](https://user-images.githubusercontent.com/75162215/128033616-da6abc37-dadb-48fe-8c17-1596de9892a5.jpg)
The other is the suspended background process, Seems like something is timing out - but it may be of no value to you - not a programmer myself..
![taskmanager](https://user-images.githubusercontent.com/75162215/128033787-3220abe3-0587-4e26-85d2-c9730eac5b43.jpg)

**Comment by FoxtrotSierra6829** [comment] 2021-08-04 13:08
I'm still reading but didn't have too much time recently and didn't have too much of an Idea why the issue occurs either, as the logs seem to be normal. The information about the suspended process could be an explanation for the program behaving weird, as it is only designed to be open in one task, but that's just a quick thought and not based on actual facts.

**Comment by mathieru** [comment] 2021-12-18 09:54
Hello !
I have the same problem. Have you been able to find a solution?
Thanks a lot

**Comment by mspann** [comment] 2022-04-15 10:01
Problem still there for me.

**Comment by Benjozork** [comment] 2022-08-03 15:37
This may improve with v3.3.0, which will buffer less things into RAM and move the install code into another thread.

**Comment by mspann** [comment] 2022-08-05 07:18
Downloaded the latest version of the installer yesterday via the Website.
No change in behavior. Not sure if this is related to RAM - my machine has plenty free.

**Comment by Benjozork** [comment] 2022-12-03 18:18
> Downloaded the latest version of the installer yesterday via the Website. No change in behavior. Not sure if this is related to RAM - my machine has plenty free.

This was not released at the time you made this comment - can you try again ?

**Comment by mspann** [comment] 2022-12-22 20:15
Solved for me.
Thank you!

**Comment by FoxtrotSierra6829** [comment] 2022-12-30 12:15
Closing. If you still encounter this problem on a current version, open a new issue please.

**Closed by FoxtrotSierra6829** 2022-12-30 12:15 UTC
Labels: Bug, Waiting For Response
