### ISSUE TITLE
[BUG] INSERT TITLE HERE

### ISSUE THREAD

**Issue by notl3ks** [flybywiresim/installer#211] opened 2021-04-04 02:47 UTC
**Installer Version**
Latest at time of report.

**Describe the bug**

Installer eating up system memory after being closed, and still reported in Task Manager as still running, even though it's not open. Task Manager reported FBW Installer was using all my available system memory.

**To Reproduce**

I'm not sure how to re-produce, it just happened after exiting MSFS and no other programs/apps were running.

**Expected behavior**

**Additional context**

Discord username (if different from GitHub):

**Comment by FoxtrotSierra6829** [comment] 2021-04-04 10:05
Duplicate of #106 

also please add a title next time

**Closed** 2021-04-04 10:05 UTC
Labels: Bug, Duplicate
