### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by Glosemeyer** [flybywiresim/installer#328] opened 2021-12-02 07:26 UTC
### Installer Version

2.1.1

### Description

could you give us a description, what you have changed from development update to new development update ?

**Comment by GhostEagle68** [comment] 2021-12-02 08:59
You can view the commits here https://github.com/flybywiresim/a32nx/commits/master

**Comment by FoxtrotSierra6829** [comment] 2021-12-02 10:05
duplicate of #76

**Closed by FoxtrotSierra6829** 2021-12-02 10:05 UTC
