### ISSUE TITLE
[BUG] Installer ram memory consumption

### ISSUE THREAD

**Issue by Arthvr96** [flybywiresim/installer#200] opened 2021-03-27 22:02 UTC
**Installer Version**
1.1.3

**Describe the bug**
Huge consumption of ram memory.
After closing the installer window, the process in the task manager was still active.

I downloaded the mod in the experimental version using the installer and closed the installer.
After a few hours, the computer started to freeze. In the task manager I found this:

![Bez tytułu](https://user-images.githubusercontent.com/50343711/112736189-08576400-8f51-11eb-8604-324682ba7f45.png)

**To Reproduce**
Considering how long it took for this error to occur, I didn't have time to try to reproduce it completely.

**Additional context**
Due to the fact that I did not have time to try to reproduce this error, I will describe the steps I took on the computer the first time until I noticed the problem.

1. Start Installer app 
2. Install experimential mod 
3. Close installator 
4. Run game (I was playing for 3 hours)
5. Exit game
6. Doing other things on the computer for 3-4 hours (I'm watching a movie)

After 6th point I noticed the computer freezing and found the installer process in the task manager.

I ran the installer several times, each time, I downloaded the mod, then I closed the installer and checked if the process also disappeared in the task manager.
In this case, he always disappeared.

**Comment by ternium1** [comment] 2021-03-27 22:31
I have the same issue, I left the installer running while playing Rainbow Six Siege, suddenly the game crashed, windows explorer restarted and FBW Installer consumed 17GB of RAM.

**Comment by ternium1** [comment] 2021-03-27 22:43
(Also Duplicate of #106 )

**Closed** 2021-03-28 00:25 UTC
Labels: Bug
