### ISSUE TITLE
Display date and time of latest build on buttons

### ISSUE THREAD

**Issue by NickyNiclas** [flybywiresim/installer#293] opened 2021-09-18 01:49 UTC
### Installer Version

2.0.1

### Description

I would love to see the date of the latest build on the development and experimental buttons. I just feel like it should be visible somewhere for clarity.

### References (optional)

![Screenshot 2021-09-18 033834](https://user-images.githubusercontent.com/40072565/133868174-498f5a56-3cb8-4d3e-ba90-2aa884d63591.png)

**Comment by FoxtrotSierra6829** [comment] 2021-09-19 17:31
Duplicate of #68

**Closed** 2021-09-19 17:31 UTC
Labels: Enhancement
