### ISSUE TITLE
Installer crash when InstalledPackagesPath is not default location

### ISSUE THREAD

**Issue by PixelHunter88** [flybywiresim/installer#277] opened 2021-07-31 07:05 UTC
### Installer Version

1.2.0

### Describe the bug

When starting the app it crashes.

The reason is assumingly that my PackagePath is moved to another path like described here:
https://forums.flightsimulator.com/t/move-msfs2020-to-new-drive/250773/3

Because I want all my FS files on the fastest SSD drive.
FS2020 runs without any issue.

When I install the files manually everything works perfect as well.

Thank you so much for this great piece of software!

### Expected behavior

The installer should respect the InstalledPackagesPath configuration without crashing.

### Steps to reproduce

Edit the value for InstalledPackagesPath to a new desired location at the bottom of the UserCfg.opt file located in
C:\Users\Your username\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalCache

Then start the installer.

### References (optional)

![grafik](https://user-images.githubusercontent.com/62633299/127731745-82652e79-a6f3-48fc-9c90-413d9a9c6664.png)

### Discord Username (optional)

PixelHunter#9229

**Comment by PixelHunter88** [comment] 2021-07-31 08:14
BenW provided me a workaround via Discord, to prevent the crash:
https://discord.com/channels/738864299392630914/785976111875751956/870941504615612436

**Comment by FoxtrotSierra6829** [comment] 2021-08-01 18:24
duplicate of #258

**Closed by FoxtrotSierra6829** 2021-08-01 18:24 UTC
Labels: Bug
