### ISSUE TITLE
[BUG] Cant' reinstall after changing the path of game

### ISSUE THREAD

**Issue by 1scarecrow** [flybywiresim/installer#264] opened 2021-06-27 04:35 UTC
**Installer Version**
12.0
**Describe the bug**

A error message came up when I open the setup.exe after moving the game from D: to H:. The message mainly said it couldn't dir to the new path. 
After deleted all the files in C:\Users\Steven\AppData\Local\fbw_installer and uninstallation, the issue still was there.
**To Reproduce**

1.Move the game from D: to H:
2.Open the setup.exe
3.Dir error comes out

**Expected behavior**

Maybe a config document for user to change the dir path or other things?

**Additional context**

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by FoxtrotSierra6829** [comment] 2021-06-28 09:48
Duplicate of #258

**Closed by FoxtrotSierra6829** 2021-06-28 09:48 UTC
Labels: Bug
